name: on_before_merge

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

jobs:
  merge_queue_things:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: debug
        run: |
          echo "current branch: ${{ github.ref }}"
          echo "event name: ${{ github.event_name }}"