name: on_feature_branch_change
on:
  push:
    branches-ignore:
      - main

jobs:
  validate_branch:
    runs-on: ubuntu-22.04
    steps:
      - name: validate project
        uses: csaxton-ls/my_new_ci_cd_pipeline/.github/actions/validate@make_thing

  do_the_things:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: debug
        run: |
          ls -a
          echo "current branch: ${{ github.ref }}"
          echo "event name: ${{ github.event_name }}"
          echo "repository: ${{ github.repository }}"